// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {automation} from '../models';
import {context} from '../models';

export function GetSettings():Promise<automation.Config>;

export function OnShutdown(arg1:context.Context):Promise<void>;

export function StartSocketServer():Promise<string>;

export function StopSocketServer():Promise<void>;

export function UpdateSettings(arg1:automation.Config):Promise<void>;
